version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: /home/circleci/circleci-demo-workflows
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  bundle_dependencies:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: /home/circleci/circleci-demo-workflows
    steps:
      - run: ls -aslh /home/circleci/circleci-demo-workflows
      - attach_workspace:
          at: /home/circleci/circleci-demo-workflows
      - run: ls -aslh /home/circleci/circleci-demo-workflows
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/circleci-demo-workflows/vendor/bundle
      - persist_to_workspace:
          root: .
          paths: vendor/bundle

  rake_test:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: /home/circleci/circleci-demo-workflows
    steps:
      - attach_workspace:
          at: ~/circleci-demo-workflows
      - attach_workspace:
          at: ~/circleci-demo-workflows/vendor/bundle
      - run: bundle --path vendor/bundle
      - run: bundle exec rake db:create db:schema:load
      - run:
          name: Run tests
          command: bundle exec rake

  precompile_assets:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: /home/circleci/circleci-demo-workflows
    steps:
      - attach_workspace:
          at: ~/circleci-demo-workflows
      - attach_workspace:
          at: ~/circleci-demo-workflows/vendor/bundle
      - run: bundle --path vendor/bundle
      - run:
          name: Precompile assets
          command: bundle exec rake assets:precompile
      - persist_to_workspace:
          root: .
          paths: public/assets

  deploy:
    machine:
        enabled: true
    working_directory: /home/circleci/circleci-demo-workflows
    environment:
      - HEROKU_APP: still-shelf-38337
    steps:
      - attach_workspace:
          at: ~/circleci-demo-workflows
      - attach_workspace:
          at: ~/circleci-demo-workflows/vendor/bundle
      - attach_workspace:
          at: ~/circleci-demo-workflows/public/assets
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh
      - run:
          command: |
            git push heroku workspace-forwarding:master
            heroku run rake db:migrate
            sleep 5 # sleep for 5 seconds to wait for dynos
            heroku restart

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - rake_test:
          requires:
            - checkout_code
            - bundle_dependencies
      - precompile_assets:
          requires:
            - checkout_code
            - bundle_dependencies
      - deploy:
          requires:
            - checkout_code
            - rake_test
            - precompile_assets
